/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NestedRecord, Primitive, SubmitField } from "apie-form-elements/dist/types/components";
export { NestedRecord, Primitive, SubmitField } from "apie-form-elements/dist/types/components";
export namespace Components {
    interface ApieUglyForm {
        "initialValue"?: NestedRecord<SubmitField>;
        "internalState": NestedRecord<Primitive>;
        "polymorphicFormDefinition"?: Record<string, string>;
        "validationErrors": NestedRecord<string>;
        "value": NestedRecord<SubmitField>;
    }
    interface ApieUglyTest {
    }
}
declare global {
    interface HTMLApieUglyFormElement extends Components.ApieUglyForm, HTMLStencilElement {
    }
    var HTMLApieUglyFormElement: {
        prototype: HTMLApieUglyFormElement;
        new (): HTMLApieUglyFormElement;
    };
    interface HTMLApieUglyTestElement extends Components.ApieUglyTest, HTMLStencilElement {
    }
    var HTMLApieUglyTestElement: {
        prototype: HTMLApieUglyTestElement;
        new (): HTMLApieUglyTestElement;
    };
    interface HTMLElementTagNameMap {
        "apie-ugly-form": HTMLApieUglyFormElement;
        "apie-ugly-test": HTMLApieUglyTestElement;
    }
}
declare namespace LocalJSX {
    interface ApieUglyForm {
        "initialValue"?: NestedRecord<SubmitField>;
        "internalState"?: NestedRecord<Primitive>;
        "polymorphicFormDefinition"?: Record<string, string>;
        "validationErrors"?: NestedRecord<string>;
        "value"?: NestedRecord<SubmitField>;
    }
    interface ApieUglyTest {
    }
    interface IntrinsicElements {
        "apie-ugly-form": ApieUglyForm;
        "apie-ugly-test": ApieUglyTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "apie-ugly-form": LocalJSX.ApieUglyForm & JSXBase.HTMLAttributes<HTMLApieUglyFormElement>;
            "apie-ugly-test": LocalJSX.ApieUglyTest & JSXBase.HTMLAttributes<HTMLApieUglyTestElement>;
        }
    }
}
